import React from 'react';
import { Helmet } from 'react-helmet-async';
import { Link } from 'react-router-dom';
import logo from '../../assets/Frame4ico.png';
import {
  FileText,
  CheckCircle,
  XCircle,
  Scale,
  AlertTriangle,
  Globe,
  RefreshCw,
  Mail,
  Calendar,
  ArrowLeft,
  Palette,
  Shield,
  Users,
  Copyright,
  Gavel,
} from 'lucide-react';
import './Legal.css';

const LAST_UPDATED = 'January 5, 2026';

const SECTIONS = [
  {
    id: 'acceptance',
    icon: CheckCircle,
    title: 'Acceptance of Terms',
    content: `By accessing or using CColorPalette ("the Service"), you agree to be bound by these Terms of Service ("Terms"). If you do not agree to these Terms, please do not use the Service.

These Terms constitute a legally binding agreement between you and CColorPalette. We may update these Terms from time to time, and your continued use of the Service after any changes constitutes acceptance of the new Terms.

The Service is intended for users who are at least 13 years of age. By using the Service, you represent that you meet this age requirement.`,
  },
  {
    id: 'description',
    icon: Palette,
    title: 'Description of Service',
    content: `CColorPalette is a free online color palette generator that allows users to:

- Generate random color palettes using various harmony modes
- Customize and adjust colors within palettes
- Lock specific colors while regenerating others
- Check color accessibility and contrast ratios
- Simulate color blindness to test palette accessibility
- Export palettes in various formats (CSS, Tailwind, JSON, PNG, SVG, etc.)
- Share palettes via unique URLs
- Access palette history during a session

The Service is provided "as is" and "as available" without warranties of any kind. We reserve the right to modify, suspend, or discontinue any aspect of the Service at any time without notice.`,
  },
  {
    id: 'permitted-use',
    icon: CheckCircle,
    title: 'Permitted Use',
    content: `You are granted a limited, non-exclusive, non-transferable license to use CColorPalette for lawful purposes. You MAY:

**Personal Use**
- Generate unlimited color palettes for personal projects
- Save and bookmark palette URLs for future reference
- Share palette URLs with others

**Commercial Use**
- Use generated palettes in commercial projects
- Incorporate colors into products, websites, apps, or designs
- Use exported code (CSS, Tailwind, etc.) in commercial software
- Create designs for clients using palettes from CColorPalette

**Educational Use**
- Use the Service for learning about color theory
- Include screenshots in educational materials with attribution
- Demonstrate the tool in workshops or presentations

All palettes generated are free to use without attribution, though we appreciate credit when possible.`,
  },
  {
    id: 'prohibited-use',
    icon: XCircle,
    title: 'Prohibited Use',
    content: `You agree NOT to use CColorPalette to:

**Technical Abuse**
- Attempt to gain unauthorized access to our systems or servers
- Use automated scripts, bots, or scrapers to access the Service excessively
- Interfere with or disrupt the Service or servers
- Attempt to reverse engineer, decompile, or disassemble the Service
- Circumvent any security measures or access restrictions

**Harmful Activities**
- Transmit malware, viruses, or other harmful code
- Engage in any activity that could damage, disable, or impair the Service
- Use the Service in any way that violates applicable laws or regulations

**Misrepresentation**
- Claim ownership of or take credit for the CColorPalette tool itself
- Misrepresent your affiliation with CColorPalette
- Create derivative services that could be confused with CColorPalette

**Commercial Restrictions**
- Resell access to the Service
- Create a competing service by directly copying our interface or code
- Use our branding, logos, or trademarks without permission

Violation of these terms may result in termination of access to the Service.`,
  },
  {
    id: 'intellectual-property',
    icon: Copyright,
    title: 'Intellectual Property',
    content: `**Our Intellectual Property**

The CColorPalette name, logo, website design, and underlying code are owned by us and protected by intellectual property laws. You may not use our branding without written permission.

**Your Generated Content**

Color palettes you generate using CColorPalette are not owned by us. You retain full rights to use any color combinations you create for any purpose.

However, please note:
- Colors themselves cannot be copyrighted
- The same or similar palettes may be generated by other users
- We make no claims of uniqueness or exclusivity for any generated palette

**Open Standards**

Color values (hex codes, RGB, HSL, etc.) are mathematical representations and are not proprietary. Export formats like CSS and JSON are open standards.

**Third-Party Content**

Any third-party libraries, fonts, or icons used in the Service are subject to their respective licenses. Our use of such content does not transfer any rights to you beyond what is permitted by those licenses.`,
  },
  {
    id: 'disclaimer',
    icon: AlertTriangle,
    title: 'Disclaimer of Warranties',
    content: `THE SERVICE IS PROVIDED "AS IS" AND "AS AVAILABLE" WITHOUT WARRANTIES OF ANY KIND, EITHER EXPRESS OR IMPLIED.

**We Do Not Warrant That:**
- The Service will be uninterrupted, error-free, or secure
- Any defects will be corrected
- The Service will meet your specific requirements
- Results obtained from the Service will be accurate or reliable
- Generated palettes will be suitable for any particular purpose

**Color Accuracy**

Colors may appear differently on different devices, monitors, and in different lighting conditions. We cannot guarantee color accuracy across all displays. For critical color work, always verify colors using calibrated equipment.

**Accessibility Claims**

While we provide WCAG contrast checking tools, we do not guarantee that palettes will meet all accessibility requirements for your specific use case. You are responsible for ensuring your designs meet applicable accessibility standards.

**Professional Advice**

CColorPalette is a tool, not professional design advice. For important projects, consider consulting with professional designers or color specialists.`,
  },
  {
    id: 'limitation-liability',
    icon: Scale,
    title: 'Limitation of Liability',
    content: `TO THE MAXIMUM EXTENT PERMITTED BY LAW, CCOLORPALETTE AND ITS OWNERS, OPERATORS, EMPLOYEES, AND AGENTS SHALL NOT BE LIABLE FOR:

**Direct Damages**
- Any direct damages arising from your use of or inability to use the Service

**Indirect Damages**
- Lost profits, revenue, or business opportunities
- Loss of data or data corruption
- Consequential, incidental, special, or punitive damages
- Any damages arising from third-party claims

**Specific Exclusions**
- Damages resulting from reliance on any information obtained through the Service
- Damages resulting from unauthorized access to your data
- Damages arising from any interruption or cessation of the Service

This limitation applies regardless of the legal theory (contract, tort, strict liability, or otherwise) and even if we have been advised of the possibility of such damages.

Some jurisdictions do not allow certain limitations of liability, so some of these limitations may not apply to you.`,
  },
  {
    id: 'indemnification',
    icon: Shield,
    title: 'Indemnification',
    content: `You agree to indemnify, defend, and hold harmless CColorPalette, its owners, operators, employees, agents, and affiliates from and against any claims, damages, losses, liabilities, costs, and expenses (including reasonable attorneys' fees) arising from:

- Your use of the Service
- Your violation of these Terms
- Your violation of any rights of another party
- Your violation of any applicable laws or regulations
- Any content you create using the Service that infringes on third-party rights

This indemnification obligation will survive termination of these Terms and your use of the Service.`,
  },
  {
    id: 'modifications',
    icon: RefreshCw,
    title: 'Modifications to Service and Terms',
    content: `**Service Modifications**

We reserve the right to modify, suspend, or discontinue any part of the Service at any time, with or without notice. This includes:
- Adding or removing features
- Changing the user interface
- Updating export formats
- Modifying accessibility tools

We will not be liable to you or any third party for any modification, suspension, or discontinuation of the Service.

**Terms Modifications**

We may revise these Terms at any time by updating this page. Changes become effective immediately upon posting. Your continued use of the Service after changes are posted constitutes acceptance of the modified Terms.

For significant changes, we may provide additional notice on our website. We encourage you to review these Terms periodically.

The "Last Updated" date at the top of this page indicates when these Terms were last revised.`,
  },
  {
    id: 'governing-law',
    icon: Gavel,
    title: 'Governing Law and Disputes',
    content: `**Governing Law**

These Terms shall be governed by and construed in accordance with the laws of the jurisdiction in which CColorPalette operates, without regard to conflict of law principles.

**Dispute Resolution**

Any disputes arising from these Terms or your use of the Service shall be resolved through:

1. **Informal Resolution:** We encourage you to contact us first to resolve any issues informally.

2. **Binding Arbitration:** If informal resolution fails, disputes shall be resolved through binding arbitration rather than in court, except where prohibited by law.

3. **Class Action Waiver:** You agree to resolve disputes on an individual basis and waive any right to participate in class action lawsuits or class-wide arbitration.

**Exceptions**

Nothing in this section prevents either party from seeking injunctive relief in court for intellectual property infringement or other urgent matters.

**Severability**

If any provision of these Terms is found to be unenforceable, the remaining provisions will continue in full force and effect.`,
  },
  {
    id: 'general',
    icon: Globe,
    title: 'General Provisions',
    content: `**Entire Agreement**

These Terms, together with our Privacy Policy, constitute the entire agreement between you and CColorPalette regarding the Service and supersede any prior agreements.

**Waiver**

Our failure to enforce any right or provision of these Terms shall not constitute a waiver of such right or provision.

**Assignment**

You may not assign or transfer these Terms or your rights hereunder without our prior written consent. We may assign these Terms without restriction.

**No Third-Party Beneficiaries**

These Terms do not create any third-party beneficiary rights.

**Headings**

Section headings are for convenience only and do not affect the interpretation of these Terms.

**Survival**

Provisions that by their nature should survive termination shall survive, including intellectual property, disclaimer, limitation of liability, and indemnification sections.`,
  },
  {
    id: 'contact',
    icon: Mail,
    title: 'Contact Information',
    content: `If you have questions about these Terms of Service, please contact us:

**Email:** legal@ccolorpalette.com

**Response Time:** We aim to respond to all inquiries within 14 business days.

For privacy-related questions, please see our Privacy Policy or contact privacy@ccolorpalette.com.

For general questions about using CColorPalette, please visit our FAQ section on the homepage.`,
  },
];

function TermsOfService() {
  return (
    <div className="legal-page">
      <Helmet>
        <title>Terms of Service | CColorPalette</title>
        <meta
          name="description"
          content="Terms of Service for CColorPalette - Understand the terms and conditions for using our free color palette generator."
        />
        <link rel="canonical" href="https://ccolorpalette.com/terms" />
      </Helmet>

      {/* Header */}
      <header className="legal-header">
        <div className="legal-header-container">
            <Link to="/home" className="header-logo">
                <img src={logo} alt="CColorPalette" className="header-logo-img" />
                <span className="header-logo-text">CColorPalette</span>
            </Link>

          <Link to="/home" className="legal-back-link">
            <ArrowLeft size={18} />
            <span>Back to Home</span>
          </Link>
        </div>
      </header>

      {/* Hero */}
      <section className="legal-hero">
        <div className="legal-hero-container">
          <div className="legal-hero-icon">
            <FileText size={32} />
          </div>
          <h1 className="legal-hero-title">Terms of Service</h1>
          <p className="legal-hero-subtitle">
            Please read these terms carefully before using CColorPalette.
          </p>
          <div className="legal-hero-meta">
            <Calendar size={14} />
            <span>Last updated: {LAST_UPDATED}</span>
          </div>
        </div>
      </section>

      {/* Table of Contents */}
      <nav className="legal-toc">
        <div className="legal-toc-container">
          <h2 className="legal-toc-title">Contents</h2>
          <ul className="legal-toc-list">
            {SECTIONS.map((section) => (
              <li key={section.id}>
                <a href={`#${section.id}`} className="legal-toc-link">
                  <section.icon size={14} />
                  <span>{section.title}</span>
                </a>
              </li>
            ))}
          </ul>
        </div>
      </nav>

      {/* Content */}
      <main className="legal-content">
        <div className="legal-content-container">
          {SECTIONS.map((section) => (
            <section key={section.id} id={section.id} className="legal-section">
              <div className="legal-section-header">
                <div className="legal-section-icon">
                  <section.icon size={20} />
                </div>
                <h2 className="legal-section-title">{section.title}</h2>
              </div>
              <div className="legal-section-content">
                {section.content.split('\n\n').map((paragraph, index) => {
                  if (paragraph.startsWith('**') && paragraph.endsWith('**')) {
                    return (
                      <h3 key={index} className="legal-subsection-title">
                        {paragraph.replace(/\*\*/g, '')}
                      </h3>
                    );
                  }
                  if (paragraph.startsWith('**')) {
                    const parts = paragraph.split('**').filter(Boolean);
                    return (
                      <div key={index}>
                        <h3 className="legal-subsection-title">{parts[0]}</h3>
                        {parts[1] && <p>{parts[1]}</p>}
                      </div>
                    );
                  }
                  if (paragraph.startsWith('- ')) {
                    const items = paragraph.split('\n').filter((line) => line.startsWith('- '));
                    return (
                      <ul key={index} className="legal-list">
                        {items.map((item, i) => (
                          <li key={i}>{item.replace('- ', '')}</li>
                        ))}
                      </ul>
                    );
                  }
                  if (paragraph.match(/^\d+\./)) {
                    const items = paragraph.split('\n').filter((line) => line.match(/^\d+\./));
                    return (
                      <ol key={index} className="legal-list legal-list-ordered">
                        {items.map((item, i) => (
                          <li key={i}>{item.replace(/^\d+\.\s*/, '')}</li>
                        ))}
                      </ol>
                    );
                  }
                  if (paragraph === paragraph.toUpperCase() && paragraph.length > 50) {
                    return (
                      <p key={index} className="legal-emphasis">
                        {paragraph}
                      </p>
                    );
                  }
                  return <p key={index}>{paragraph}</p>;
                })}
              </div>
            </section>
          ))}
        </div>
      </main>

      {/* Footer */}
      <footer className="legal-footer">
        <div className="legal-footer-container">
          <div className="legal-footer-links">
            <Link to="/home">Home</Link>
            <Link to="/">Generator</Link>
            <Link to="/privacy">Privacy Policy</Link>
          </div>
          <p className="legal-footer-copyright">
            &copy; {new Date().getFullYear()} CColorPalette. All rights reserved.
          </p>
        </div>
      </footer>
    </div>
  );
}

export default TermsOfService;